# Site
title: HSG Nürnberg
description: >- # this means to ignore newlines until "baseurl:"
  Internetpräsenz der privilegierten Hauptschützengesellschaft Nürnberg 1429
bio:                'HSG'
locale:             de_DE
baseurl: "" # the subpath of your site, e.g. /aktuelles
url: "https://www.hsg-nbg.de" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/aktuelles/:title/"
    layout: post
    author:

# Jekyll
permalink:          /aktuelles/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
github:             HSG1429

# personal
location: >-
  Günthersbühler Str. 145, 90491 Nürnberg (Erlenstegen)
phone:              0911 / 59 29 63
email:              phsg@online.de

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/aktuelles/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, ruby]
